; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28107.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Alex\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
